
@CoreHRAPI_HostAddress = http://localhost:5113

### Auth Endpoints

# Login
POST https://localhost:7237/api/v1/auth/login
Content-Type: application/json

{
    "username":"admin",
    "password":"12345678"
}

# Logout
POST {{CoreHRAPI_HostAddress}}/api/v1/auth/logout
Accept: application/json

# Forgot Password
POST {{CoreHRAPI_HostAddress}}/api/v1/auth/forgot-password
Content-Type: application/json

{
    "email": "your-email@example.com"
}

### Dashboard Endpoints

# Get User Details
GET {{CoreHRAPI_HostAddress}}/api/v1/dashboard/user/details/0000000001
Accept: application/json

### Reports Endpoints

# Get All Cases
GET {{CoreHRAPI_HostAddress}}/api/v1/reports
Accept: application/json

# Get Case by ID
GET {{CoreHRAPI_HostAddress}}/api/v1/reports/find/{id}
Accept: application/json

# Create Case
POST {{CoreHRAPI_HostAddress}}/api/v1/reports/create
Content-Type: application/json

{
    "caseProperty1": "value1",
    "caseProperty2": "value2"
}

# Update Case
PUT {{CoreHRAPI_HostAddress}}/api/v1/reports/update/{id}
Content-Type: application/json

{
    "caseProperty1": "newValue1",
    "caseProperty2": "newValue2"
}

# Delete Case
DELETE {{CoreHRAPI_HostAddress}}/api/v1/reports/delete/{id}
Accept: application/json

# Get Case Statistics
GET {{CoreHRAPI_HostAddress}}/api/v1/reports/statistics
Accept: application/json

# Upload Master List
POST {{CoreHRAPI_HostAddress}}/api/v1/reports/upload-masterlist
Content-Type: multipart/form-data

# Insert Master List
POST {{CoreHRAPI_HostAddress}}/api/v1/reports/upload-masterlist/accept
Accept: application/json
```
